### ISSUE TITLE
Error 404 when getting hist name

### ISSUE THREAD

**Issue by killdres** [georgyo/ifconfig.io#19]
"404 page not found" appears when 'http://ifconfig.io/host' is typed

**Comment by georgyo** [comment]
I broke this unintentionally a long time ago during a refactor. I haven't fixed it because doing a reverse lookup requires doing a DNS lookup, and the world of reverse lookup DNS servers are a sad bunch. This put a lot of strain with thousands of requests waiting for a DNS lookup.

It has been my intention to fix it but have not had the time or motivation to do so. I'll gladly take a PR to fix it, or I might try to find time this weekend.

**Comment by georgyo** [comment]
Actually, it was a simpler fix than I realized. This is fixed and live.
