### ISSUE TITLE
Unstable service recently

### ISSUE THREAD

**Issue by leesah** [georgyo/ifconfig.io#2]
The site becomes very unstable recently. I am guessing this is the original repository of the project. Is there anything the community can help with?

**Comment by georgyo** [comment]
Thanks for reaching out. I originally put the service behind cloudflare because that increases the last mile connection time significantly. However, the keep alive they are using is now upwards of 40k concurrent connections, which is apparently causing some instability.

I removed cloudflare for the time being, so latency should go up, but it should be more reliable.

**Comment by georgyo** [comment]
Made some tweeks to the server. Testing shows it can handle north of 100k connections now. Looks pretty good now.
