### ISSUE TITLE
IP Address and Remote Host showing server's private IP, rather than connecting IP.

### ISSUE THREAD

**Issue by Entheologian** [georgyo/ifconfig.io#43]
Hi,

I tried this and when connecting externally, the IP Address and Remote Host are showing my server's IP (192.168.x.x in my case) rather than the client connecting IP. The ifconfig.io is running via docker, behind an nginx proxy.

X-Forwarded-For on the page output shows the proper public connecting IP, as does the $ curl ifconfig.io/forwarded command on the page, but the other curl commands are showing 192.168.x.x.

 Is there something specific that I would need to configure for this to work like http://ifconfig.io?

**Comment by georgyo** [comment]
This because we default to using the cloudflare header instead of the more standard X-FORWARDED-FOR.

https://github.com/georgyo/ifconfig.io/blob/4bf77e678842df279aeb54daf8a0f4813c0cbcdf/main.go#L40

You can set the `FORWARD_IP_HEADER` environment variable to `X-FORWARDED-FOR` to solve your issue. It would also might make sense to change the default. If you submit a patch for that, I'll merge it.
