### ISSUE TITLE
Show Used DNS Server

### ISSUE THREAD

**Issue by MartinHennrich** [georgyo/ifconfig.io#63]
Would it be possible to show the used DNS server?
What do you think about this?

**Comment by georgyo** [comment]
This is actually pretty tricky to do. To implement this, you need to have each client request a never before use DNS name, and then have the DNS server and webserver talking to each other conveying which DNS server was used. As soon as multiple requests for the same domain happen, it is impossible to know which client used which DNS server .

I do think it would be interesting to make such a service that is usable by curl. Basically curl a domain, it gives you a 302 http redirect to a random subdomain and then return the DNS server that resolved that subdomain. That would be kinda awesome.

I may get around to make something like that one day, but in the meantime I recommend https://ipleak.net/ 

I don't know if this goes against their terms of service but you can script how they do detection like this
```bash
#!/usr/bin/env bash
SESSION=$(tr -dc a-z0-9 </dev/urandom | head -c 40)
for i in {1..10}; do
    curl "https://${SESSION}-${i}.ipleak.net/dnsdetection/"
    sleep 1
done
```

You need to do multiple requests because you may have several different DNS servers you use. And the sleep is also necessary to get accurate counts.

Please don't hammer their API, they are one the better sites for detecting IP leakage and I hate for them to have a impossible flood of automated usage of their service.

**Comment by MartinHennrich** [comment]
> This is actually pretty tricky to do. To implement this, you need to have each client request a never before use DNS name, and then have the DNS server and webserver talking to each other conveying which DNS server was used. As soon as multiple requests for the same domain happen, it is impossible to know which client used which DNS server .
> 
> I do think it would be interesting to make such a service that is usable by curl. Basically curl a domain, it gives you a 302 http redirect to a random subdomain and then return the DNS server that resolved that subdomain. That would be kinda awesome.
> 
> I may get around to make something like that one day, but in the meantime I recommend https://ipleak.net/
> 
> I don't know if this goes against their terms of service but you can script how they do detection like this
> 
> ```shell
> #!/usr/bin/env bash
> SESSION=$(tr -dc a-z0-9 </dev/urandom | head -c 40)
> for i in {1..10}; do
>     curl "https://${SESSION}-${i}.ipleak.net/dnsdetection/"
>     sleep 1
> done
> ```
> 
> You need to do multiple requests because you may have several different DNS servers you use. And the sleep is also necessary to get accurate counts.
> 
> Please don't hammer their API, they are one the better sites for detecting IP leakage and I hate for them to have a impossible flood of automated usage of their service.

Thanks for your detailed reply. 
I will use their service only a few times per month.
