### ISSUE TITLE
Either ask for donations or sell traffic to cloudflare. 

### ISSUE THREAD

**Issue by alithechemist** [georgyo/ifconfig.io#74]
Right now the website is trying to set two cookies from third parties:

 - static.cloudflareinsights.com
 - cdnjs.cloudflare.com

***This looks like purely user tracking.***

Please use a self hosted analytics solution like Matomo, in order to protect the privacy of your users.
Also I see a monero wallet address for donations in the bottom of the page..
So is this a commercial product or not?
Do you have a privacy policy?

Thanks in advance.

**Comment by xavier-hernandez** [comment]
cdnjs.cloudflare.com, appears to be for the ribbon displayed in the right-hand corner

I assume the monero wallet address is for donations since it's free, and they probably lose money due to hosting it

I have a variation of this code https://miip.io and use analytics as well. I don't have a donation button on mine because of all the sites I've created for open source I've never gotten a dime so I just quit asking.

**Comment by alithechemist** [comment]
Thank you for removing cloudflareinsight.com, that's a great start!

Unfortunately cloudflare is a MITM proxy by definition and you trust them with your SSL private key and if they want they can prevent some people from accessing contents, or they can change the contents, inject js etc.


Why would you trust them?  i mean ... really why?

By removing cloudflareinsight.com,  you only removed your own access to the analytics I'm afraid. They keep collecting users data thanks to the cdn.

I mean if those few lines of css were to be part of the html, would it be so bad for you? 

On top of that, if as you say, this is not making you any money, then you should not be afraid of a DDOS.
I'm not sure of your past experiences, but I think giving them the SSL certificate for convenience is just wrong.

Anyway i really appreciate that you removed analytics, at same time to be honest i know that this doesn't change anything on crimeflare side in terms of data colleciton, as you use them as reverse proxy

**Comment by alithechemist** [comment]
> Because I am not making money I shouldn't care if my service is down? What kind of logic is that?

**THE LOGIC OF A CHALLENGE.**

So: a website is experiencing difficulties related to high traffic and voila' cloudflare comes and solves the problem, at the price that from now on they can even change the contents for certain clients.

Convenience is not all, i hope : https://decloudflare.crimeflare.eu.org/#deCloudflare=readme/en.md

> The code is mighty simple

well yes, 
```
$_SERVER['REMOTE_ADDR']
```
This should do.

**Comment by xavier-hernandez** [comment]
DDOS is not a challenge. It can happen to anyone for any reason. I just had a server under a DDOS attack without even a website on it. You'd have to find a provider that can stop and circumvent the DDOS attack and not charge an arm and a leg for it. If you want to do it yourself, you'd need load balancers and multiple servers which costs money. Cloudflare provides those services for free. If other providers offered that service for free, Cloudflare wouldn't be as big has it is now.

On another note, there isn't a form on his website where you can insert private information, so I'm not sure what the issue is from an SSL perspective.

Since this is an open-source product. As said previously, you can host it on your own server and avoid these "security" risks.

**Comment by alithechemist** [comment]
maybe you can consider EU?
https://www.hetzner.com/unternehmen/ddos-schutz/
